<?php

namespace Database\Seeders;

use App\Models\Nationalite;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class NationaliteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Schema::disableForeignKeyConstraints();

        Nationalite::truncate();

        Schema::enableForeignKeyConstraints();

        /**
         * Ne pas toucher à @var $record
         */

        $record = [
            ['code' => 'AW', 'nationalite' => 'Aruba'],
            ['code' => 'AF', 'nationalite' => 'Afghanistan'],
            ['code' => 'AO', 'nationalite' => 'Angola'],
            ['code' => 'AL', 'nationalite' => 'Albania'],
            ['code' => 'AD', 'nationalite' => 'Andorra'],
            ['code' => 'AE', 'nationalite' => 'United Arab Emirates'],
            ['code' => 'AR', 'nationalite' => 'Argentina'],
            ['code' => 'AM', 'nationalite' => 'Armenia'],
            ['code' => 'AS', 'nationalite' => 'American Samoa'],
            ['code' => 'AG', 'nationalite' => 'Antigua and Barbuda'],
            ['code' => 'AU', 'nationalite' => 'Australia'],
            ['code' => 'AT', 'nationalite' => 'Austria'],
            ['code' => 'AZ', 'nationalite' => 'Azerbaijan'],
            ['code' => 'BI', 'nationalite' => 'Burundi'],
            ['code' => 'BE', 'nationalite' => 'Belgium'],
            ['code' => 'BJ', 'nationalite' => 'Benin'],
            ['code' => 'BF', 'nationalite' => 'Burkina Faso'],
            ['code' => 'BD', 'nationalite' => 'Bangladesh'],
            ['code' => 'BG', 'nationalite' => 'Bulgaria'],
            ['code' => 'BH', 'nationalite' => 'Bahrain'],
            ['code' => 'BS', 'nationalite' => 'Bahamas, The'],
            ['code' => 'BA', 'nationalite' => 'Bosnia and Herzegovina'],
            ['code' => 'BY', 'nationalite' => 'Belarus'],
            ['code' => 'BZ', 'nationalite' => 'Belize'],
            ['code' => 'BM', 'nationalite' => 'Bermuda'],
            ['code' => 'BO', 'nationalite' => 'Bolivia'],
            ['code' => 'BR', 'nationalite' => 'Brazil'],
            ['code' => 'BB', 'nationalite' => 'Barbados'],
            ['code' => 'BN', 'nationalite' => 'Brunei Darussalam'],
            ['code' => 'BT', 'nationalite' => 'Bhutan'],
            ['code' => 'BW', 'nationalite' => 'Botswana'],
            ['code' => 'CF', 'nationalite' => 'Central African Republic'],
            ['code' => 'CA', 'nationalite' => 'Canada'],
            ['code' => 'CH', 'nationalite' => 'Switzerland'],
            ['code' => 'JG', 'nationalite' => 'Channel Islands'],
            ['code' => 'CL', 'nationalite' => 'Chile'],
            ['code' => 'CN', 'nationalite' => 'China'],
            ['code' => 'CI', 'nationalite' => 'Cote d\'Ivoire'],
            ['code' => 'CM', 'nationalite' => 'Cameroon'],
            ['code' => 'CD', 'nationalite' => 'Congo, Dem. Rep.'],
            ['code' => 'CG', 'nationalite' => 'Congo, Rep.'],
            ['code' => 'CO', 'nationalite' => 'Colombia'],
            ['code' => 'KM', 'nationalite' => 'Comoros'],
            ['code' => 'CV', 'nationalite' => 'Cabo Verde'],
            ['code' => 'CR', 'nationalite' => 'Costa Rica'],
            ['code' => 'CU', 'nationalite' => 'Cuba'],
            ['code' => 'CW', 'nationalite' => 'Curacao'],
            ['code' => 'KY', 'nationalite' => 'Cayman Islands'],
            ['code' => 'CY', 'nationalite' => 'Cyprus'],
            ['code' => 'CZ', 'nationalite' => 'Czech Republic'],
            ['code' => 'DE', 'nationalite' => 'Germany'],
            ['code' => 'DJ', 'nationalite' => 'Djibouti'],
            ['code' => 'DM', 'nationalite' => 'Dominica'],
            ['code' => 'DK', 'nationalite' => 'Denmark'],
            ['code' => 'DO', 'nationalite' => 'Dominican Republic'],
            ['code' => 'DZ', 'nationalite' => 'Algeria'],
            ['code' => 'EC', 'nationalite' => 'Ecuador'],
            ['code' => 'EG', 'nationalite' => 'Egypt, Arab Rep.'],
            ['code' => 'ER', 'nationalite' => 'Eritrea'],
            ['code' => 'ES', 'nationalite' => 'Spain'],
            ['code' => 'EE', 'nationalite' => 'Estonia'],
            ['code' => 'ET', 'nationalite' => 'Ethiopia'],
            ['code' => 'FI', 'nationalite' => 'Finland'],
            ['code' => 'FJ', 'nationalite' => 'Fiji'],
            ['code' => 'FR', 'nationalite' => 'France'],
            ['code' => 'FO', 'nationalite' => 'Faroe Islands'],
            ['code' => 'FM', 'nationalite' => 'Micronesia, Fed. Sts.'],
            ['code' => 'GA', 'nationalite' => 'Gabon'],
            ['code' => 'GB', 'nationalite' => 'United Kingdom'],
            ['code' => 'GE', 'nationalite' => 'Georgia'],
            ['code' => 'GH', 'nationalite' => 'Ghana'],
            ['code' => 'GI', 'nationalite' => 'Gibraltar'],
            ['code' => 'GN', 'nationalite' => 'Guinea'],
            ['code' => 'GM', 'nationalite' => 'Gambia, The'],
            ['code' => 'GW', 'nationalite' => 'Guinea-Bissau'],
            ['code' => 'GQ', 'nationalite' => 'Equatorial Guinea'],
            ['code' => 'GR', 'nationalite' => 'Greece'],
            ['code' => 'GD', 'nationalite' => 'Grenada'],
            ['code' => 'GL', 'nationalite' => 'Greenland'],
            ['code' => 'GT', 'nationalite' => 'Guatemala'],
            ['code' => 'GU', 'nationalite' => 'Guam'],
            ['code' => 'GY', 'nationalite' => 'Guyana'],
            ['code' => 'HK', 'nationalite' => 'Hong Kong SAR, China'],
            ['code' => 'HN', 'nationalite' => 'Honduras'],
            ['code' => 'HR', 'nationalite' => 'Croatia'],
            ['code' => 'HT', 'nationalite' => 'Haiti'],
            ['code' => 'HU', 'nationalite' => 'Hungary'],
            ['code' => 'ID', 'nationalite' => 'Indonesia'],
            ['code' => 'IM', 'nationalite' => 'Isle of Man'],
            ['code' => 'IN', 'nationalite' => 'India'],
            ['code' => 'IE', 'nationalite' => 'Ireland'],
            ['code' => 'IR', 'nationalite' => 'Iran, Islamic Rep.'],
            ['code' => 'IQ', 'nationalite' => 'Iraq'],
            ['code' => 'IS', 'nationalite' => 'Iceland'],
            ['code' => 'IL', 'nationalite' => 'Israel'],
            ['code' => 'IT', 'nationalite' => 'Italy'],
            ['code' => 'JM', 'nationalite' => 'Jamaica'],
            ['code' => 'JO', 'nationalite' => 'Jordan'],
            ['code' => 'JP', 'nationalite' => 'Japan'],
            ['code' => 'KZ', 'nationalite' => 'Kazakhstan'],
            ['code' => 'KE', 'nationalite' => 'Kenya'],
            ['code' => 'KG', 'nationalite' => 'Kyrgyz Republic'],
            ['code' => 'KH', 'nationalite' => 'Cambodia'],
            ['code' => 'KI', 'nationalite' => 'Kiribati'],
            ['code' => 'KN', 'nationalite' => 'St. Kitts and Nevis'],
            ['code' => 'KR', 'nationalite' => 'Korea, Rep.'],
            ['code' => 'KW', 'nationalite' => 'Kuwait'],
            ['code' => 'LA', 'nationalite' => 'Lao PDR'],
            ['code' => 'LB', 'nationalite' => 'Lebanon'],
            ['code' => 'LR', 'nationalite' => 'Liberia'],
            ['code' => 'LY', 'nationalite' => 'Libya'],
            ['code' => 'LC', 'nationalite' => 'St. Lucia'],
            ['code' => 'LI', 'nationalite' => 'Liechtenstein'],
            ['code' => 'LK', 'nationalite' => 'Sri Lanka'],
            ['code' => 'LS', 'nationalite' => 'Lesotho'],
            ['code' => 'LT', 'nationalite' => 'Lithuania'],
            ['code' => 'LU', 'nationalite' => 'Luxembourg'],
            ['code' => 'LV', 'nationalite' => 'Latvia'],
            ['code' => 'MO', 'nationalite' => 'Macao SAR, China'],
            ['code' => 'MF', 'nationalite' => 'St. Martin (French part)'],
            ['code' => 'MA', 'nationalite' => 'Morocco'],
            ['code' => 'MC', 'nationalite' => 'Monaco'],
            ['code' => 'MD', 'nationalite' => 'Moldova'],
            ['code' => 'MG', 'nationalite' => 'Madagascar'],
            ['code' => 'MV', 'nationalite' => 'Maldives'],
            ['code' => 'MX', 'nationalite' => 'Mexico'],
            ['code' => 'MH', 'nationalite' => 'Marshall Islands'],
            ['code' => 'MK', 'nationalite' => 'Macedonia, FYR'],
            ['code' => 'ML', 'nationalite' => 'Mali'],
            ['code' => 'MT', 'nationalite' => 'Malta'],
            ['code' => 'MM', 'nationalite' => 'Myanmar'],
            ['code' => 'ME', 'nationalite' => 'Montenegro'],
            ['code' => 'MN', 'nationalite' => 'Mongolia'],
            ['code' => 'MP', 'nationalite' => 'Northern Mariana Islands'],
            ['code' => 'MZ', 'nationalite' => 'Mozambique'],
            ['code' => 'MR', 'nationalite' => 'Mauritania'],
            ['code' => 'MU', 'nationalite' => 'Mauritius'],
            ['code' => 'MW', 'nationalite' => 'Malawi'],
            ['code' => 'MY', 'nationalite' => 'Malaysia'],
            ['code' => 'NA', 'nationalite' => 'Namibia'],
            ['code' => 'NC', 'nationalite' => 'New Caledonia'],
            ['code' => 'NE', 'nationalite' => 'Niger'],
            ['code' => 'NG', 'nationalite' => 'Nigeria'],
            ['code' => 'NI', 'nationalite' => 'Nicaragua'],
            ['code' => 'NL', 'nationalite' => 'Netherlands'],
            ['code' => 'NO', 'nationalite' => 'Norway'],
            ['code' => 'NP', 'nationalite' => 'Nepal'],
            ['code' => 'NR', 'nationalite' => 'Nauru'],
            ['code' => 'NZ', 'nationalite' => 'New Zealand'],
            ['code' => 'OM', 'nationalite' => 'Oman'],
            ['code' => 'PK', 'nationalite' => 'Pakistan'],
            ['code' => 'PA', 'nationalite' => 'Panama'],
            ['code' => 'PE', 'nationalite' => 'Peru'],
            ['code' => 'PH', 'nationalite' => 'Philippines'],
            ['code' => 'PW', 'nationalite' => 'Palau'],
            ['code' => 'PG', 'nationalite' => 'Papua New Guinea'],
            ['code' => 'PL', 'nationalite' => 'Poland'],
            ['code' => 'PR', 'nationalite' => 'Puerto Rico'],
            ['code' => 'KP', 'nationalite' => 'Korea, Dem. People’s Rep.'],
            ['code' => 'PT', 'nationalite' => 'Portugal'],
            ['code' => 'PY', 'nationalite' => 'Paraguay'],
            ['code' => 'PS', 'nationalite' => 'West Bank and Gaza'],
            ['code' => 'PF', 'nationalite' => 'French Polynesia'],
            ['code' => 'QA', 'nationalite' => 'Qatar'],
            ['code' => 'RO', 'nationalite' => 'Romania'],
            ['code' => 'RU', 'nationalite' => 'Russian Federation'],
            ['code' => 'RW', 'nationalite' => 'Rwanda'],
            ['code' => 'SA', 'nationalite' => 'Saudi Arabia'],
            ['code' => 'SD', 'nationalite' => 'Sudan'],
            ['code' => 'SN', 'nationalite' => 'Senegal'],
            ['code' => 'SG', 'nationalite' => 'Singapore'],
            ['code' => 'SB', 'nationalite' => 'Solomon Islands'],
            ['code' => 'SL', 'nationalite' => 'Sierra Leone'],
            ['code' => 'SV', 'nationalite' => 'El Salvador'],
            ['code' => 'SM', 'nationalite' => 'San Marino'],
            ['code' => 'SO', 'nationalite' => 'Somalia'],
            ['code' => 'RS', 'nationalite' => 'Serbia'],
            ['code' => 'SS', 'nationalite' => 'South Sudan'],
            ['code' => 'ST', 'nationalite' => 'Sao Tome and Principe'],
            ['code' => 'SR', 'nationalite' => 'Suriname'],
            ['code' => 'SK', 'nationalite' => 'Slovak Republic'],
            ['code' => 'SI', 'nationalite' => 'Slovenia'],
            ['code' => 'SE', 'nationalite' => 'Sweden'],
            ['code' => 'SZ', 'nationalite' => 'Swaziland'],
            ['code' => 'SX', 'nationalite' => 'Sint Maarten (Dutch part)'],
            ['code' => 'SC', 'nationalite' => 'Seychelles'],
            ['code' => 'SY', 'nationalite' => 'Syrian Arab Republic'],
            ['code' => 'TC', 'nationalite' => 'Turks and Caicos Islands'],
            ['code' => 'TD', 'nationalite' => 'Chad'],
            ['code' => 'TG', 'nationalite' => 'Togo'],
            ['code' => 'TH', 'nationalite' => 'Thailand'],
            ['code' => 'TJ', 'nationalite' => 'Tajikistan'],
            ['code' => 'TM', 'nationalite' => 'Turkmenistan'],
            ['code' => 'TL', 'nationalite' => 'Timor-Leste'],
            ['code' => 'TO', 'nationalite' => 'Tonga'],
            ['code' => 'TT', 'nationalite' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'nationalite' => 'Tunisia'],
            ['code' => 'TR', 'nationalite' => 'Turkey'],
            ['code' => 'TV', 'nationalite' => 'Tuvalu'],
            ['code' => 'TW', 'nationalite' => 'Taiwan, China'],
            ['code' => 'TZ', 'nationalite' => 'Tanzania'],
            ['code' => 'UG', 'nationalite' => 'Uganda'],
            ['code' => 'UA', 'nationalite' => 'Ukraine'],
            ['code' => 'UY', 'nationalite' => 'Uruguay'],
            ['code' => 'US', 'nationalite' => 'United States'],
            ['code' => 'UZ', 'nationalite' => 'Uzbekistan'],
            ['code' => 'VC', 'nationalite' => 'St. Vincent and the Grenadines'],
            ['code' => 'VE', 'nationalite' => 'Venezuela, RB'],
            ['code' => 'VG', 'nationalite' => 'British Virgin Islands'],
            ['code' => 'VI', 'nationalite' => 'Virgin Islands (U.S.)'],
            ['code' => 'VN', 'nationalite' => 'Vietnam'],
            ['code' => 'VU', 'nationalite' => 'Vanuatu'],
            ['code' => 'WS', 'nationalite' => 'Samoa'],
            ['code' => 'XK', 'nationalite' => 'Kosovo'],
            ['code' => 'YE', 'nationalite' => 'Yemen, Rep.'],
            ['code' => 'ZA', 'nationalite' => 'South Africa'],
            ['code' => 'ZM', 'nationalite' => 'Zambia'],
            ['code' => 'ZW', 'nationalite' => 'Zimbabwe'],
        ];

        DB::table('nationalites')->insert($record);

    }
}
